### ISSUE TITLE
Feature Request: RadListView functionality

### ISSUE THREAD

**Issue by MCurran16** [nativescript-community/ui-collectionview#18]
To be a viable alternative to the RadListView, it needs to implement all of its functionality.

- Swipe to delete
- Pull to refresh

These are two major ones that are missing.

Thank you

**Comment by farfromrefug** [comment]
it does not try to be an alternative to rlv. people are switching  from rlv because it is "big" and slow. collectionview aim to be fast and simple. 
pull to refresh is already existing in other plugins (and compatible with collection view)
as for swipe right now won't happen as i did not find good native libs to do that .
plus whatever happens I will only happen as another plugin on top of collectionview. just like the waterfall layout. 
You are welcome to work on it if you want.
I will close that issue as I think I answered the done and won't do here.
